# inad legacy =)
# dedicated to those who are with us from the very beginning and to those who with us from seredining

# server specific
server:
  shutdown: graceful
  servlet:
    session:
      timeout: 20m
      cookie:
        http-only: true
    application-display-name: challeng.er
  compression:
    enabled: true
    min-response-size: 2KB # default value and I like it here
    mime-types: "text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml, image/jpeg, image/png, application/octet-stream"

# spring specific
spring:
  application:
    name: challeng.er
  main:
    lazy-initialization: true
    web-application-type: servlet
    banner-mode: console # yeah bitch!
  jackson:
    time-zone: UTC
    locale: en_US
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/challenger?currentSchema=challenger"
    username: "user"
    password: "P@55w0rd"
    initialization-mode: never
    hikari:
      minimumIdle: 5
      maximumPoolSize: 21
      autoCommit: false
      connection-timeout: 1000
      pool-name: "hikari-pool"
  flyway:
    enabled: true
    locations: classpath:db/migration/dev
    url: "jdbc:postgresql://localhost:5432/challenger"
    user: "user"
    password: "P@55w0rd"
    connect-retries: 3
    schemas: "challenger"
